addSong = do ->
  n = 0
  alnum = (s) ->
    s.replace(/[^a-z0-9]/gi, '').toUpperCase()

  (artist, title) ->
    setTimeout ->
      $.getJSON "http://tinysong.com/s/#{artist.replace(/\ /gi,'+')}+#{title.replace(/\ /gi,'+')}?format=json&key=b5478a15b5aac312162a553448478c6a&callback=wat", (songs) ->
        return if not songs.length # Check if array

        bestMatchesArtist = false
        bestMatchesTitle = false
        bestSong = null

        for song in songs
          if alnum(song.ArtistName) == alnum(artist)
            song.matchesArtist = true
          if alnum(song.SongName) == alnum(title)
            song.matchesTitle = true

          if song.matchesTitle and song.matchesArtist
            Grooveshark.addSongsByID([song.SongID])
            console.log(song)
            return

        # Nothing looked so great -- add the first one
        console.log(songs[0])
        Grooveshark.addSongsByID([songs[0].SongID])
    , 100 * n++

tracks = [
  {title:"Eat My Beat",artist:"Air"},
  {title:"Woman and Man",artist:"Ween"},
  {title:"Missing The Light Of The Day",artist:"Air"},
  {title:"Goodbye Stranger",artist:"Supertramp"},
  {title:"Die",artist:"Girls"},
  {title:"Vomit",artist:"Girls"},
  {title:"Longview",artist:"Green Day"},
  {title:"Basket Case",artist:"Green Day"},
  {title:"Burnout",artist:"Green Day"},
  {title:"F.O.D.- All By Myself",artist:"Green Day"},
  {title:"Honey Bunny",artist:"Girls"},
  {title:"Next Girl",artist:"The Black Keys"},
  {title:"Forgiveness",artist:"Girls"},
  {title:"Father Time",artist:"Animal Collective"},
  {title:"Wayne's Pet Youngun'",artist:"Ween"},
  {title:"Cold &amp; Wet",artist:"Ween"},
  {title:"Common Bitch",artist:"Ween"},
  {title:"Nan",artist:"Ween"},
  {title:"Learnin' to Love",artist:"Ween"},
  {title:"Self Esteem",artist:"The Offspring"},
  {title:"Me-Jane",artist:"PJ Harvey"},
  {title:"Helplessness Blues",artist:"Fleet Foxes"},
  {title:"Even If You Don't",artist:"Ween"},
  {title:"Reagan's Skeleton",artist:"Yeasayer"},
  {title:"The Shrine / An Argument",artist:"Fleet Foxes"},
  {title:"There Is A Burning Ball Of Fire In Outer Space",artist:"Kids &amp; Explosions"},
  {title:"Safe in the Steep Cliffs",artist:"Emancipator"},
  {title:"Siberian Breaks",artist:"MGMT"},
  {title:"drivetime",artist:"Shadow Dancer"},
  {title:"Naomi",artist:"Neutral Milk Hotel"},
  {title:"Gardenhead - Leave Me Alone",artist:"Neutral Milk Hotel"},
  {title:"Holland, 1945",artist:"Neutral Milk Hotel"},
  {title:"Beach Comber",artist:"Real Estate"},
  {title:"Nevergreen",artist:"Emancipator"},
  {title:"Civilization",artist:"Justice"},
  {title:"She Comes Alive",artist:"Baby Monster"},
  {title:"Nothin' In The World Can Stop Me From Worryin' 'Bout That Girl",artist:"The Kinks"},
  {title:"O Katrina!",artist:"Black Lips"},
  {title:"Waka/Jawaka",artist:"Frank Zappa"},
  {title:"Pain and Pleasure",artist:"The Residents"},
  {title:"Crime Of The Century",artist:"Supertramp"},
  {title:"Rudy",artist:"Supertramp"},
  {title:"Balance",artist:"Funkadelic"},
  {title:"The Worse It Gets",artist:"Penguin Prison"},
  {title:"Girlsrock",artist:"Siriusmo"},
  {title:"Family Tree",artist:"Black Lips"},
  {title:"Rosebush Inside (Morees Bickham)",artist:"Sean Hayes"},
  {title:"Sunshine Recorder",artist:"Boards of Canada"},
  {title:"Music Is Math",artist:"Boards of Canada"},
  {title:"House of Usher (Inside)",artist:"Geggy Tah"},
  {title:"Don't Close the Door",artist:"Geggy Tah"},
  {title:"The Book I Read",artist:"Talking Heads"},
  {title:"Vordhosbn",artist:"Aphex Twin"},
  {title:"Bluish",artist:"Animal Collective"},
  {title:"Summertime Clothes",artist:"Animal Collective"},
  {title:"The cost of resistance",artist:"Xploding Plastix"},
  {title:"Fantasy",artist:"Dye"},
  {title:"Blackout",artist:"David Bowie"},
  {title:"When My Train Pulls In - Live [Solo Acoustic]",artist:"Gary Clark Jr."},
  {title:"When My Train Pulls In (Live) [Solo Acoustic]",artist:"Gary Clark Jr."},
  {title:"Music for My Mother",artist:"Funkadelic"},
  {title:"Skin Is, My",artist:"Andrew Bird"},
  {title:"Social Construct",artist:"Reggie Watts"},
  {title:"Goldene Kugel",artist:"Siriusmo"},
  {title:"Easy Meat",artist:"Frank Zappa"},
  {title:"Leavin' Blues",artist:"Davy Graham"},
  {title:"Tarana",artist:"Ravi Shankar"},
  {title:"April Come She Will",artist:"Simon &amp; Garfunkel"},
  {title:"Brother",artist:"Edward Sharpe &amp; The Magnetic Zeros"},
  {title:"I'm So Green",artist:"Can"},
  {title:"Mommy, What's A Funkadelic",artist:"Funkadelic"},
  {title:"Kissed by a kisser",artist:"Xploding Plastix"},
  {title:"The Famous Biting Guy",artist:"Xploding Plastix"},
  {title:"Houdini",artist:"Foster the People"},
  {title:"Listening Wind",artist:"Talking Heads"},
  {title:"City Smasher ~ Beach Ninjas",artist:"Norrin Radd"},
  {title:"Most Of The Time",artist:"Bob Dylan"},
  {title:"Wow (Modeselektor Edit)",artist:"Siriusmo"},
  {title:"You Won't Get With Me Tonight",artist:"Weezer"},
  {title:"Congratulations",artist:"MGMT"},
  {title:"To Catch a Thief",artist:"Lovage"},
  {title:"This Year",artist:"The Mountain Goats"},
  {title:"Nova Baby",artist:"The Black Keys"},
  {title:"Little Black Submarines",artist:"The Black Keys"},
  {title:"Can You Get to That",artist:"Funkadelic"},
  {title:"Maggot Brain",artist:"Funkadelic"},
  {title:"Skillet (Good 'n' Greasy)",artist:"Davy Graham"},
  {title:"Don't Think Twice, It's Alright",artist:"Davy Graham"},
  {title:"Hit It and Quit It",artist:"Funkadelic"},
  {title:"Tiger Phone Card",artist:"Dengue Fever"},
  {title:"Mood for a Day",artist:"Yes"},
  {title:"What's on Your Mind (Pure Energy)",artist:"Information Society"},
  {title:"Did You See Me?",artist:"Ween"},
  {title:"Gabrielle",artist:"Ween"},
  {title:"Somebody That I Used to Know",artist:"Gotye"},
  {title:"Tastes Good on Th' Bun",artist:"Ween"},
  {title:"Run-Around",artist:"Blues Traveler"},
  {title:"Composure",artist:"Warpaint"},
  {title:"Your Love Is (A Metaphor)",artist:"Paul and Storm"},
  {title:"Big Swifty",artist:"Frank Zappa"},
  {title:"Girl From the North Country",artist:"Bob Dylan"},
  {title:"Ultra Thizz",artist:"Rustie"},
  {title:"Hover Traps",artist:"Rustie"},
  {title:"Source Decay",artist:"The Mountain Goats"},
  {title:"The Elements: Fire (Mrs. O’Leary’s Cow)",artist:"The Beach Boys"},
  {title:"Jeffer",artist:"Boys Noize"},
  {title:"Oh!",artist:"Boys Noize"},
  {title:"Sanctimonious Sam",artist:"Horace Silver"},
  {title:"Comatose Luck",artist:"Xploding Plastix"},
  {title:"Treat Me Mean, I Need the Reputation",artist:"Xploding Plastix"},
  {title:"Prashanti",artist:"Ravi Shankar"},
  {title:"Regiment",artist:"Brian Eno &amp; David Byrne"},
  {title:"Viaje",artist:"Jason Webley"},
  {title:"Still Sound",artist:"Toro y Moi"},
  {title:"Thanks Vision",artist:"Toro y Moi"},
  {title:"It Will All End In Tears",artist:"The Drums"},
  {title:"Who Needs the Peace Corps",artist:"Frank Zappa"},
  {title:"Broken Hearts Are for Assholes",artist:"Frank Zappa"},
  {title:"Silver Trembling Hands",artist:"The Flaming Lips"},
  {title:"Vitamin C",artist:"Can"},
  {title:"Got Blinded",artist:"Toro y Moi"},
  {title:"Don't Fuck With My Money",artist:"Penguin Prison"},
  {title:"A Funny Thing",artist:"Penguin Prison"},
  {title:"Lions",artist:"tUnE-yArDs"},
  {title:"Bizness",artist:"tUnE-yArDs"},
  {title:"It Just Might Be a One-shot Deal",artist:"Frank Zappa"},
  {title:"A Horse Called Golgotha",artist:"Baroness"},
  {title:"Swollen and Halo",artist:"Baroness"},
  {title:"Two Weeks",artist:"Grizzly Bear"},
  {title:"While You Wait for the Others",artist:"Grizzly Bear"},
  {title:"Future Sick",artist:"Neon Indian"},
  {title:"Ooh La La",artist:"Faces"},
  {title:"Dawn Chorus",artist:"Boards of Canada"},
  {title:"Take Five",artist:"Davy Graham"},
  {title:"Song Against Sex",artist:"Neutral Milk Hotel"},
  {title:"Avril 14th",artist:"Aphex Twin"},
  {title:"On the Beach",artist:"Faces"},
  {title:"Whoever You Are",artist:"Geggy Tah"},
  {title:"Birthday Boy",artist:"Ween"},
  {title:"Skippin' Town",artist:"The Drums"},
  {title:"El Scorcho",artist:"Weezer"},
  {title:"Alspacka",artist:"The Tuss"},
  {title:"Only A Friend",artist:"Dengue Fever"},
  {title:"Dastard",artist:"Dufus"},
  {title:"3/4 A.D.",artist:"Davy Graham &amp; Alexis Korner"},
  {title:"Jingle Of A Dog's Collar",artist:"Butthole Surfers"},
  {title:"Andean Ocean Mixtape",artist:"Javelin"},
  {title:"Two Little Men In A Flying Saucer",artist:"Ella Fitzgerald"},
  {title:"Bicycle",artist:"Memory Tapes"},
  {title:"It Ain't Easy",artist:"David Bowie"},
  {title:"Suffer Little Children",artist:"The Smiths"},
  {title:"Biology 2",artist:"Halfnelson"},
  {title:"Roger",artist:"Halfnelson"},
  {title:"Saccharin And The War",artist:"Halfnelson"},
  {title:"Eleven",artist:"Primus"},
  {title:"Up on the Roof",artist:"Les Claypool's Frog Brigade"},
  {title:"David Makalaster",artist:"Les Claypool's Frog Brigade"},
  {title:"D's Diner",artist:"Les Claypool's Frog Brigade"},
  {title:"Tiny Girls",artist:"Iggy Pop"},
  {title:"Brian Eno",artist:"MGMT"},
  {title:"Goodbye Sober Day",artist:"Mr. Bungle"},
  {title:"Carousel",artist:"Mr. Bungle"},
  {title:"Golem II: The Bionic Vapour Boy",artist:"Mr. Bungle"},
  {title:"Rome",artist:"Yeasayer"},
  {title:"O.N.E.",artist:"Yeasayer"},
  {title:"81",artist:"Joanna Newsom"},
  {title:"Good Intentions Paving Co.",artist:"Joanna Newsom"},
  {title:"Off My Mind",artist:"Javelin"},
  {title:"Black Sands",artist:"Bonobo"},
  {title:"It Must Be a Camel",artist:"Frank Zappa"},
  {title:"Calcutta Cutie",artist:"Horace Silver"},
  {title:"Lament 1, \"Bird's Lament\"",artist:"Moondog"},
  {title:"1997 (Tonight We're Gonna Party Like It's...)",artist:"Sleepytime Gorilla Museum"},
  {title:"Little Birdy",artist:"Ween"},
  {title:"Big Jilm",artist:"Ween"},
  {title:"Sarah",artist:"Ween"},
  {title:"Mutilated Lips",artist:"Ween"},
  {title:"Tick",artist:"Ween"},
  {title:"Stillness Is the Move",artist:"Dirty Projectors"},
  {title:"On It on It",artist:"Javelin"},
  {title:"Hang On To Your Ego (Bonus Track)",artist:"The Beach Boys"},
  {title:"Grievances",artist:"Daniel Johnston"},
  {title:"Lovers' Carvings",artist:"Bibio"},
  {title:"Haikuesque (When She Laughs)",artist:"Bibio"},
  {title:"The Handshake",artist:"MGMT"},
  {title:"Home",artist:"LCD Soundsystem"},
  {title:"Mr. Ambulance Driver",artist:"The Flaming Lips"},
  {title:"The W.A.N.D.",artist:"The Flaming Lips"},
  {title:"Whale",artist:"George &amp; Jonathan"},
  {title:"I Want You (She's So Heavy)",artist:"The Beatles"},
  {title:"Big Business Monkey",artist:"Daniel Johnston"},
  {title:"Walking The Cow",artist:"Daniel Johnston"},
  {title:"Ram On",artist:"Paul &amp; Linda McCartney"},
  {title:"Uncle Albert/Admiral Halsey",artist:"Paul &amp; Linda McCartney"},
  {title:"Guys Eyes",artist:"Animal Collective"},
  {title:"Bend Over",artist:"Wagon Christ"},
  {title:"Breakbeat Metal Music",artist:"Luke Vibert"},
  {title:"Last One Awake (Friend Version)",artist:"Memory Cassette"},
  {title:"The Mess Inside",artist:"The Mountain Goats"},
  {title:"The Best Ever Death Metal Band in Denton",artist:"The Mountain Goats"},
  {title:"Color in Your Cheeks",artist:"The Mountain Goats"},
  {title:"Yuki Satellites",artist:"Rymdlego"},
  {title:"Paparazzi",artist:"Shugo Tokumaru"},
  {title:"Future Umbrella",artist:"Shugo Tokumaru"},
  {title:"Girls",artist:"高木正勝"},
  {title:"Gwely Mernans",artist:"Alarm Will Sound"},
  {title:"Reddening: Blood of the Pelican",artist:"Miasma &amp; The Carousel Of Headless Horses"},
  {title:"Gevurah",artist:"John Zorn"},
  {title:"The Owl in Daylight",artist:"Secret Chiefs 3"},
  {title:"Wildflower",artist:"Nostalgia 77"},
  {title:"Last Nine Days",artist:"quasimode"},
  {title:"Terrapin",artist:"The Quantic Soul Orchestra"},
  {title:"An Introduction",artist:"The Broken Keys"},
  {title:"The Conspirator (Main Theme)",artist:"The Quantic Soul Orchestra"},
  {title:"Dirge",artist:"Nostalgia 77"},
  {title:"Blue Head",artist:"Idiot Flesh"},
  {title:"Genius of Love",artist:"Tom Tom Club"},
  {title:"Cordova",artist:"De Facto"},
  {title:"The Dragon",artist:"Groundation"},
  {title:"Comandante Che Guevara",artist:"Compay Segundo"},
  {title:"Ice",artist:"Crack the Sky"},
  {title:"Concrete &amp; Clay",artist:"Unit 4 + 2"},
  {title:"Sunflower River Blues",artist:"Jack Rose"},
  {title:"Watermelon in Easter Hay",artist:"Frank Zappa"},
  {title:"Riding",artist:"Palace Brothers"},
  {title:"Old River (live on KZSU)",artist:"Beatbeat Whisper"},
  {title:"Untitled 1",artist:"Will Oldham"},
  {title:"For Slavoj",artist:"A Hawk and a Hacksaw"},
  {title:"Knoxville Blues",artist:"John Fahey"},
  {title:"Wooden Empire",artist:"Noah Georgeson"},
  {title:"Storm Warning",artist:"Lyn Taitt and His Comets"},
  {title:"Foggy Mountain Breakdown",artist:"Gil Trythall"},
  {title:"Run",artist:"Air"},
  {title:"Paranoid Android",artist:"Brad Mehldau"},
  {title:"Things Behind the Sun",artist:"Brad Mehldau"},
  {title:"Travelin' Light",artist:"Widespread Panic"},
  {title:"Ri Na Cruinne",artist:"Clannad"},
  {title:"Four Dead Guys Waltz",artist:"Chris Thile"},
  {title:"Maiden Voyage",artist:"Herbie Hancock"},
  {title:"Spain",artist:"Chick Corea"},
  {title:"Sun Gonna Shine In My Back Door Someday Blues",artist:"John Fahey"},
  {title:"Light Flight",artist:"The Pentangle"},
  {title:"They Don't Make Them Like You Anymore",artist:"Rory Gallagher"},
  {title:"Polly On The Shore",artist:"Trees"},
  {title:"Sheep Season",artist:"Mellow Candle"},
  {title:"Chimacum Rain",artist:"Linda Perhacs"},
  {title:"Revolt Of The Dyke Brigade",artist:"John Fahey"},
  {title:"Matty Groves",artist:"Fairport Convention"},
  {title:"Memories",artist:"Frozen Silence"},
  {title:"This Room",artist:"The Notwist"}
]

i=0
for song in tracks
  addSong(song.artist, song.title)
  ++i
