module.exports =
  port: 3033
  grooveshark_key: 'YOUR_GROOVESHARK_KEY'
  grooveshark_secret: 'YOUR_GROOVESHARK_SECRET'
  parse_app_id: 'YOUR_PARSE_APP_ID'
  parse_rest_key: 'YOUR_PARSE_REST_KEY'
  aws_access_key: 'YOUR_AWS_ACCESS_KEY'
  aws_secret: 'YOUR_AWS_SECRET'
  aws_s3_bucket: 'YOUR_AWS_BUCKET'
